-- MySQL Script generated by MySQL Workbench
-- mié 10 oct 2018 14:03:58 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema service_x_employees
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service_x_employees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service_x_employees` DEFAULT CHARACTER SET utf8 ;
USE `service_x_employees` ;

-- -----------------------------------------------------
-- Table `service_x_employees`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_x_employees`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iddepartments_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_x_employees`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_x_employees`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idemployee_states_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_x_employees`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_x_employees`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `nss` VARCHAR(255) NOT NULL,
  `salary` INT NOT NULL,
  `entry_date` DATE NOT NULL,
  `departments_id` INT NOT NULL,
  `employee_states_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idemployees_UNIQUE` (`id` ASC),
  INDEX `fk_employees_departments_idx` (`departments_id` ASC),
  INDEX `fk_employees_employee_states1_idx` (`employee_states_id` ASC),
  CONSTRAINT `fk_employees_departments`
    FOREIGN KEY (`departments_id`)
    REFERENCES `service_x_employees`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_employee_states1`
    FOREIGN KEY (`employee_states_id`)
    REFERENCES `service_x_employees`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `service_x_employees`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service_x_employees`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;

CREATE USER 'web_app' IDENTIFIED BY 'admin';

GRANT SELECT ON TABLE `service_x_employees`.* TO 'web_app';
GRANT SELECT, INSERT, TRIGGER ON TABLE `service_x_employees`.* TO 'web_app';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `service_x_employees`.* TO 'web_app';
GRANT EXECUTE ON ROUTINE `service_x_employees`.* TO 'web_app';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
